import json, uuid

services = [
  {"port": 5888, "name": "飞牛 fnOS", "category": "NAS 管理", "protocol": "http", "icon": "🐂", "description": "NAS 系统管理面板", "url": "http://YOUR_NAS_IP:5888"},
  {"port": 5889, "name": "飞牛 fnOS (SSL)", "category": "NAS 管理", "protocol": "https", "icon": "", "description": "NAS 管理面板 (HTTPS)", "url": "https://YOUR_NAS_IP:5889"},
  {"port": 9990, "name": "飞牛桌面管理", "category": "NAS 管理", "protocol": "http", "icon": "🖥️", "description": "飞牛桌面管理工具", "url": "http://YOUR_NAS_IP:9990"},
  {"port": 88, "name": "Heimdall", "category": "NAS 管理", "protocol": "http", "icon": "🏠", "description": "NAS 应用导航仪表盘", "url": "http://YOUR_NAS_IP:88"},
  {"port": 444, "name": "Heimdall (SSL)", "category": "NAS 管理", "protocol": "https", "icon": "", "description": "NAS 应用导航 (HTTPS)", "url": "https://YOUR_NAS_IP:444"},
  {"port": 10789, "name": "BestNav", "category": "NAS 管理", "protocol": "http", "icon": "🧭", "description": "飞牛NAS导航页", "url": "http://YOUR_NAS_IP:10789"},
  {"port": 2829, "name": "Nginx 默认", "category": "NAS 管理", "protocol": "http", "icon": "", "description": "Nginx 欢迎页", "url": "http://YOUR_NAS_IP:2829"},
  {"port": 3000, "name": "MoviePilot", "category": "影视媒体", "protocol": "http", "icon": "🎥", "description": "影视自动化管理工具", "url": "http://YOUR_NAS_IP:3000"},
  {"port": 8096, "name": "Emby", "category": "影视媒体", "protocol": "http", "icon": "📺", "description": "媒体服务器", "url": "http://YOUR_NAS_IP:8096"},
  {"port": 32400, "name": "Plex", "category": "影视媒体", "protocol": "http", "icon": "▶️", "description": "流媒体播放器 (需认证)", "url": "http://YOUR_NAS_IP:32400"},
  {"port": 8005, "name": "飞牛影视", "category": "影视媒体", "protocol": "http", "icon": "🎞️", "description": "飞牛原生影视应用", "url": "http://YOUR_NAS_IP:8005"},
  {"port": 3009, "name": "清和电视", "category": "影视媒体", "protocol": "http", "icon": "📡", "description": "在线电视直播", "url": "http://YOUR_NAS_IP:3009"},
  {"port": 3029, "name": "MoonTV", "category": "影视媒体", "protocol": "http", "icon": "🌙", "description": "在线影视播放平台", "url": "http://YOUR_NAS_IP:3029"},
  {"port": 8787, "name": "银河JAV", "category": "影视媒体", "protocol": "http", "icon": "🌌", "description": "GalaxyJAV 媒体管理", "url": "http://YOUR_NAS_IP:8787"},
  {"port": 45849, "name": "Go2RTC", "category": "影视媒体", "protocol": "http", "icon": "📹", "description": "WebRTC 视频流转发", "url": "http://YOUR_NAS_IP:45849"},
  {"port": 3024, "name": "IPTV 控制中心", "category": "影视媒体", "protocol": "http", "icon": "📺", "description": "IPTV 直播源管理", "url": "http://YOUR_NAS_IP:3024"},
  {"port": 8689, "name": "Leelaa Playlist", "category": "影视媒体", "protocol": "http", "icon": "📋", "description": "播放列表管理", "url": "http://YOUR_NAS_IP:8689"},
  {"port": 3020, "name": "道理鱼音乐", "category": "音乐有声", "protocol": "http", "icon": "🐟", "description": "在线音乐播放平台", "url": "http://YOUR_NAS_IP:3020"},
  {"port": 8099, "name": "SQMusic", "category": "音乐有声", "protocol": "http", "icon": "", "description": "音乐播放服务", "url": "http://YOUR_NAS_IP:8099"},
  {"port": 13378, "name": "Audiobookshelf", "category": "音乐有声", "protocol": "http", "icon": "🎧", "description": "有声书管理平台", "url": "http://YOUR_NAS_IP:13378"},
  {"port": 3019, "name": "Ting Reader", "category": "音乐有声", "protocol": "http", "icon": "🔊", "description": "自托管有声书平台", "url": "http://YOUR_NAS_IP:3019"},
  {"port": 8085, "name": "qBittorrent", "category": "下载传输", "protocol": "http", "icon": "⬇️", "description": "BT 下载客户端 Web UI", "url": "http://YOUR_NAS_IP:8085"},
  {"port": 9091, "name": "Transmission", "category": "下载传输", "protocol": "http", "icon": "", "description": "BT 下载客户端 (需认证)", "url": "http://YOUR_NAS_IP:9091"},
  {"port": 9090, "name": "hlink", "category": "下载传输", "protocol": "http", "icon": "🔗", "description": "局域网文件传输工具", "url": "http://YOUR_NAS_IP:9090"},
  {"port": 3003, "name": "天翼云盘转存", "category": "下载传输", "protocol": "http", "icon": "☁️", "description": "天翼云盘自动转存系统", "url": "http://YOUR_NAS_IP:3003"},
  {"port": 3004, "name": "Vertex", "category": "下载传输", "protocol": "http", "icon": "🔄", "description": "PT 资源自动化管理", "url": "http://YOUR_NAS_IP:3004"},
  {"port": 18787, "name": "IYUUPlus", "category": "下载传输", "protocol": "http", "icon": "📨", "description": "PT 辅助工具 (开发版)", "url": "http://YOUR_NAS_IP:18787"},
  {"port": 3006, "name": "PanSou 盘搜", "category": "下载传输", "protocol": "http", "icon": "", "description": "网盘资源搜索引擎", "url": "http://YOUR_NAS_IP:3006"},
  {"port": 9000, "name": "Portainer", "category": "开发运维", "protocol": "http", "icon": "", "description": "Docker 容器管理", "url": "http://YOUR_NAS_IP:9000"},
  {"port": 8443, "name": "Lucky", "category": "开发运维", "protocol": "https", "icon": "🍀", "description": "反向代理 / 端口转发", "url": "https://YOUR_NAS_IP:8443"},
  {"port": 7000, "name": "Lucky (HTTPS)", "category": "开发运维", "protocol": "https", "icon": "🍀", "description": "反向代理 (HTTPS)", "url": "https://YOUR_NAS_IP:7000"},
  {"port": 3011, "name": "Uptime Kuma", "category": "开发运维", "protocol": "http", "icon": "📊", "description": "服务状态监控面板", "url": "http://YOUR_NAS_IP:3011"},
  {"port": 3028, "name": "Vigil", "category": "开发运维", "protocol": "http", "icon": "", "description": "Docker 镜像监控", "url": "http://YOUR_NAS_IP:3028"},
  {"port": 3031, "name": "WorkBuddy", "category": "开发运维", "protocol": "http", "icon": "📈", "description": "用量看板", "url": "http://YOUR_NAS_IP:3031"},
  {"port": 18090, "name": "phpMyAdmin", "category": "开发运维", "protocol": "http", "icon": "🗄️", "description": "MySQL 数据库管理", "url": "http://YOUR_NAS_IP:18090"},
  {"port": 81, "name": "Nginx", "category": "开发运维", "protocol": "http", "icon": "🌐", "description": "Nginx 服务 (403)", "url": "http://YOUR_NAS_IP:81"},
  {"port": 8082, "name": "轻阅读", "category": "教育阅读", "protocol": "http", "icon": "📖", "description": "在线阅读应用", "url": "http://YOUR_NAS_IP:8082"},
  {"port": 8083, "name": "轻课堂", "category": "教育阅读", "protocol": "http", "icon": "🎓", "description": "Lite Class 教学平台", "url": "http://YOUR_NAS_IP:8083"},
  {"port": 8090, "name": "talebook", "category": "教育阅读", "protocol": "http", "icon": "", "description": "在线电子书图书馆", "url": "http://YOUR_NAS_IP:8090"},
  {"port": 9280, "name": "WizNote", "category": "教育阅读", "protocol": "http", "icon": "📝", "description": "为知笔记服务", "url": "http://YOUR_NAS_IP:9280"},
  {"port": 3012, "name": "AI 智能错题本", "category": "教育阅读", "protocol": "http", "icon": "❌", "description": "AI 驱动错题管理", "url": "http://YOUR_NAS_IP:3012"},
  {"port": 3018, "name": "字幕助手", "category": "教育阅读", "protocol": "http", "icon": "💬", "description": "影片整理与字幕下载", "url": "http://YOUR_NAS_IP:3018"},
  {"port": 3027, "name": "字幕助手 (备)", "category": "教育阅读", "protocol": "http", "icon": "💬", "description": "影片整理与字幕下载 (备用)", "url": "http://YOUR_NAS_IP:3027"},
  {"port": 5244, "name": "Alist", "category": "工具应用", "protocol": "http", "icon": "", "description": "网盘聚合文件列表", "url": "http://YOUR_NAS_IP:5244"},
  {"port": 5230, "name": "Memos", "category": "工具应用", "protocol": "http", "icon": "🗒️", "description": "自托管备忘录/笔记", "url": "http://YOUR_NAS_IP:5230"},
  {"port": 8923, "name": "QD 框架", "category": "工具应用", "protocol": "http", "icon": "✅", "description": "自动签到框架", "url": "http://YOUR_NAS_IP:8923"},
  {"port": 18230, "name": "FnMessageBot", "category": "工具应用", "protocol": "http", "icon": "🤖", "description": "飞牛消息机器人", "url": "http://YOUR_NAS_IP:18230"},
  {"port": 8901, "name": "网址收藏夹", "category": "工具应用", "protocol": "http", "icon": "🔖", "description": "个人网址书签导航", "url": "http://YOUR_NAS_IP:8901"},
  {"port": 5005, "name": "Python App", "category": "工具应用", "protocol": "http", "icon": "🐍", "description": "Werkzeug/Flask 应用", "url": "http://YOUR_NAS_IP:5005"},
  {"port": 8024, "name": "Python App (2)", "category": "工具应用", "protocol": "http", "icon": "🐍", "description": "Werkzeug/Flask 应用", "url": "http://YOUR_NAS_IP:8024"},
  {"port": 10000, "name": "视频监控", "category": "工具应用", "protocol": "http", "icon": "", "description": "EasyNVR 视频流管理", "url": "http://YOUR_NAS_IP:10000/cloud/"},
  {"port": 3001, "name": "Uvicorn API", "category": "工具应用", "protocol": "http", "icon": "⚡", "description": "FastAPI/Uvicorn 服务", "url": "http://YOUR_NAS_IP:3001"},
  {"port": 25, "name": "SMTP", "category": "基础服务", "protocol": "tcp", "icon": "📤", "description": "邮件发送服务", "url": ""},
  {"port": 110, "name": "POP3", "category": "基础服务", "protocol": "tcp", "icon": "", "description": "邮件接收服务", "url": ""},
  {"port": 143, "name": "IMAP", "category": "基础服务", "protocol": "tcp", "icon": "📬", "description": "邮件同步协议", "url": ""},
  {"port": 139, "name": "NetBIOS", "category": "基础服务", "protocol": "tcp", "icon": "📂", "description": "网络基本输入输出", "url": ""},
  {"port": 445, "name": "SMB", "category": "基础服务", "protocol": "tcp", "icon": "", "description": "Windows 文件共享", "url": ""},
  {"port": 3306, "name": "MySQL", "category": "基础服务", "protocol": "tcp", "icon": "🗄️", "description": "关系型数据库", "url": ""},
  {"port": 49152, "name": "UPnP", "category": "基础服务", "protocol": "tcp", "icon": "🔗", "description": "通用即插即用设备", "url": ""},
  {"port": 51413, "name": "Transmission 传输", "category": "基础服务", "protocol": "tcp", "icon": "⬇️", "description": "BT 传输端口", "url": ""},
]

rows = []
for i, s in enumerate(services):
    rows.append({
        "id": str(uuid.uuid4()),
        "port": s["port"],
        "name": s["name"],
        "category": s["category"],
        "protocol": s["protocol"],
        "icon": s["icon"],
        "description": s["description"],
        "url": s["url"],
        "visible": True,
        "sort_order": i,
    })

out = r"C:\Users\TerrySG\Documents\Qoder\2026-09-30\7785e984\nas-stats\data\services.json"
with open(out, "w", encoding="utf-8") as f:
    json.dump(rows, f, ensure_ascii=False, indent=2)
print(f"Created {len(rows)} services")
